# Script para configurar Git no projeto Nobre Lobo
# Execute este script no diretório do projeto

Write-Host "Configurando repositório Git para o projeto Nobre Lobo..." -ForegroundColor Green

# Verificar se estamos no diretório correto
if (Test-Path "package.json") {
    Write-Host "✓ Arquivo package.json encontrado" -ForegroundColor Green
    
    # Inicializar repositório Git
    Write-Host "Inicializando repositório Git..." -ForegroundColor Yellow
    git init
    
    # Adicionar arquivo .gitignore se não existir
    if (-not (Test-Path ".gitignore")) {
        Write-Host "Criando arquivo .gitignore..." -ForegroundColor Yellow
        @"
# Dependencies
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Build outputs
dist/
build/
.next/
out/

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage
.grunt

# Bower dependency directory
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons
build/Release

# Dependency directories
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
public

# Storybook build outputs
.out
.storybook-out
storybook-static

# Temporary folders
tmp/
temp/

# Logs
logs
*.log

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage
.grunt

# Bower dependency directory
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test
.env.production

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# Storybook build outputs
.out
.storybook-out

# Temporary folders
tmp/
temp/

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# OS generated files
Thumbs.db
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Desktop.ini

# Vite
dist-ssr
*.local

# Local env files
.env*.local

# Vercel
.vercel

# TypeScript
*.tsbuildinfo
"@ | Out-File -FilePath ".gitignore" -Encoding UTF8
    }
    
    # Adicionar todos os arquivos
    Write-Host "Adicionando arquivos ao repositório..." -ForegroundColor Yellow
    git add .
    
    # Fazer commit inicial
    Write-Host "Fazendo commit inicial..." -ForegroundColor Yellow
    git commit -m "Initial commit: Nobre Lobo website project"
    
    # Configurar repositório remoto
    Write-Host "Configurando repositório remoto..." -ForegroundColor Yellow
    git remote add origin https://github.com/adolfohrq/nobrelobo-site2.git
    
    # Fazer push para o GitHub
    Write-Host "Fazendo push para o GitHub..." -ForegroundColor Yellow
    git branch -M main
    git push -u origin main
    
    Write-Host "✓ Repositório configurado com sucesso!" -ForegroundColor Green
    Write-Host "Projeto disponível em: https://github.com/adolfohrq/nobrelobo-site2.git" -ForegroundColor Cyan
    
} else {
    Write-Host "✗ Erro: Arquivo package.json não encontrado" -ForegroundColor Red
    Write-Host "Certifique-se de estar no diretório correto do projeto" -ForegroundColor Yellow
}